use crate::perun::random;

use super::*;
use ckb_occupied_capacity::Capacity;
use ckb_testtool::ckb_types::{bytes::Bytes, packed::*, prelude::*};
use ckb_testtool::{ckb_types::core::TransactionBuilder, context::Context};
use k256::PublicKey;
use perun;
use perun::test;
use perun_common::perun_types::{Balances, Bool, ChannelState, SEC1EncodedPubKey};
use perun_common::sig::verify_signature;

const MAX_CYCLES: u64 = 10_000_000;
const CHALLENGE_DURATION_MS: u64 = 10 * 1000;

#[test]
fn test_signature() {
    // This tests the interoperability between the on-chain signature verification
    // and the key generation & signing in the perun-ckb-backend's wallet.

    // This signature was generated by the wallet in the perun-ckb-backend
    let sig_string = "3045022100cc61e5863b2bdf90a7548853557b57d7fa87b18b66b0e366143b48c9cdb6d69102206c85d95c93cd61a471daddb41395586ab3d114a9a8c9a2ae0b6d44274a94a880";
    let sig = hex::decode(sig_string).expect("decoding signature");
    let sig_bytes: Bytes = sig.into();

    // This public key was generated by the wallet in the perun-ckb-backend
    let pubkey_string = "046b1243c51c6dea522dee4a0d5f3346afcf2209746bf49acdc90220d9834a1597f34a9c86e734515c3575f8e2314fc77976b567de7764204d4e820599ca22760c";
    let pubkey = hex::decode(pubkey_string).expect("decoding pubkey");
    let pubkey_bytes: [Byte; 65] = pubkey
        .iter()
        .map(|x| (*x).into())
        .collect::<Vec<Byte>>()
        .try_into()
        .unwrap();
    SEC1EncodedPubKey::new_builder().set(pubkey_bytes).build();

    let balances_array: [Uint64; 2] = [10u64.pack(), 11u64.pack()];
    let balances = Balances::new_builder().set(balances_array).build();
    let channel_state = ChannelState::new_builder()
        .channel_id(Byte32::zero())
        .balances(balances)
        .is_final(Bool::from_bool(true))
        .version(10u64.pack())
        .build();
    let msg = channel_state.as_slice();

    verify_signature(msg, &sig_bytes, pubkey.as_slice()).expect("valid signature");
}

#[test]
fn channel_test_bench() -> Result<(), perun::Error> {
    let res = [
        test_funding_abort,
        test_multiple_disputes,
        test_successful_funding,
    ]
    .iter()
    .map(|test| {
        let mut context = Context::default();
        let pe = perun::harness::Env::new(&mut context, MAX_CYCLES, CHALLENGE_DURATION_MS)
            .expect("preparing environment");
        test(&mut context, &pe)
    })
    .collect::<Vec<_>>();
    res.into_iter().collect()
}

fn create_channel_test<P>(
    context: &mut Context,
    env: &perun::harness::Env,
    parts: &[P],
    test: impl Fn(&mut perun::channel::Channel<perun::State>) -> Result<(), perun::Error>,
) -> Result<(), perun::Error>
where
    P: perun::Account,
{
    let mut chan = perun::channel::Channel::new(context, env, parts);
    test(&mut chan)
}

fn test_funding_abort(
    context: &mut Context,
    env: &perun::harness::Env,
) -> Result<(), perun::Error> {
    let (alice, bob) = ("alice", "bob");
    let parts = [random::account(alice), random::account(bob)];
    let funding_timeout = 10;
    let funding = [
        Capacity::bytes(1000)?.as_u64(),
        Capacity::bytes(1000)?.as_u64(),
    ];
    let funding_agreement = test::FundingAgreement::new_with_capacities(
        parts.iter().cloned().zip(funding.iter().cloned()).collect(),
    );
    create_channel_test(context, env, &parts, |chan| {
        chan.with(alice)
            .open(&funding_agreement)
            .expect("opening channel");

        chan.delay(funding_timeout);

        chan.with(alice).abort().expect("aborting channel");

        chan.assert();
        Ok(())
    })
}

fn test_successful_funding(
    context: &mut Context,
    env: &perun::harness::Env,
) -> Result<(), perun::Error> {
    let (alice, bob) = ("alice", "bob");
    let parts = [random::account(alice), random::account(bob)];
    let funding = [
        Capacity::bytes(100)?.as_u64(),
        Capacity::bytes(100)?.as_u64(),
    ];
    let funding_agreement = test::FundingAgreement::new_with_capacities(
        parts.iter().cloned().zip(funding.iter().cloned()).collect(),
    );
    create_channel_test(context, env, &parts, |chan| {
        chan.with(alice)
            .open(&funding_agreement)
            .expect("opening channel");

        chan.with(bob)
            .fund(&funding_agreement)
            .expect("funding channel");

        chan.assert();
        Ok(())
    })
}

fn test_multiple_disputes(
    context: &mut Context,
    env: &perun::harness::Env,
) -> Result<(), perun::Error> {
    let (alice, bob) = ("alice", "bob");
    let parts = [random::account(alice), random::account(bob)];
    let funding = [
        Capacity::bytes(100)?.as_u64(),
        Capacity::bytes(100)?.as_u64(),
    ];
    let funding_agreement = test::FundingAgreement::new_with_capacities(
        parts.iter().cloned().zip(funding.iter().cloned()).collect(),
    );
    create_channel_test(context, env, &parts, |chan| {
        chan.with(alice)
            .open(&funding_agreement)
            .expect("opening channel");

        chan.with(bob)
            .fund(&funding_agreement)
            .expect("funding channel");

        chan.with(alice)
            .valid()
            .dispute()
            .expect("disputing channel");

        chan.with(bob).valid().dispute().expect("disputing channel");

        chan.with(alice)
            .invalid()
            .dispute()
            .expect("disputing channel");

        chan.assert();
        Ok(())
    })
}
