use core::fmt::Debug;

use ckb_std::error::SysError;
use k256::ecdsa::Error as SigError;
use molecule::error::VerificationError;

#[derive(Debug)]
#[repr(i8)]
pub enum Error {
    IndexOutOfBound = 1,
    ItemMissing,
    LengthNotEnough,
    Encoding,
    WaitFailure,
    InvalidFd,
    OtherEndClosed,
    MaxVmsSpawned,
    MaxFdsCreated,
    UnexpectedSysError,
    TypeIDError,
    InvalidDisputeMode,
    TotalSizeNotMatch,
    HeaderIsBroken,
    UnknownItem,
    OffsetsNotMatch,
    FieldCountNotMatch,
    SignatureVerificationError,
    NoArgs,
    NoWitness,
    ChannelIdMismatch,
    VersionNumberNotIncreasing,
    StateIsFinal,
    StateNotFinal,
    ChannelNotFunded,
    NotParticipant,
    SumOfBalancesNotEqual,
    OwnIndexNotFound,
    ChannelDoesNotContinue,
    MultipleMatchingOutputs,
    FundsInInputs,
    AppChannelsNotSupported,
    UndefinedBehavior,
    ChannelCellDataIsEmpty,
    // NonLedgerChannelsNotSupported,
    // VirtualChannelsNotSupported,
    ChannelStateNotEqual,
    FundingChanged,
    InvalidParentPCTSHash,
    TypeHashNotFound,
    LedgerChannelDoesNotHaveEnoughFundsForVC,
    UnequalBalanceInLockedFundsAndVirtualChannelBalance,
    ParentsOfVCInOutputHaveDifferentVCStatus,
    InvalidOutputTxForVCDisputeStart,
    OnlyChannelStatusExpectedButThatIsNotTheCase,
    InputCellForGivenParticipantNotFound,
    FundingNotInStatus,
    OwnFundingNotInOutputs,
    FundedBitStatusNotCorrect,
    StateIsFunded,
    ParentPCTSHashNotFound,
    ChannelFundWithoutChannelOutput,
    ChannelDisputeWithoutChannelOutput,
    ChannelCloseWithChannelOutput,
    ChannelForceCloseWithChannelOutput,
    ChannelAbortWithChannelOutput,
    InvalidParentsCountForVC,
    OutputCellForGivenParticipantNotFound,
    InvalidThreadToken,
    InvalidChannelId,
    StartWithNonZeroVersion,
    StartWithFinalizedState,
    InvalidPCLSCodeHash,
    InvalidPCLSHashType,
    PCLSWithArgs,
    VCLSWithArgs,
    StatusDisputed,
    StatusNotDisputed,
    FundingNotZero,
    NotAllPaid,
    TimeLockNotExpired,
    InvalidTimestamp,
    UnableToLoadAnyChannelStatus,
    UnableToLoadVirtualChannelStatus,
    InvalidSignature,
    InvalidMessage,
    InvalidPFLSInOutputs,
    InvalidNumberOfOutputs,
    PCTSNotFound,
    FoundDifferentChannel,
    MoreThanOneChannel,
    BalanceBelowPFLSMinCapacity,
    SamePaymentAddress,
    TypeScriptInPaymentOutput,
    TypeScriptInPFLSOutput,
    InvalidSUDT,
    InvalidSUDTDataLength,
    DecreasingAmount,
    WrongChannelType,
    InvalidVCTx,
    InvalidVCTxStart,
    ParentsOfVCNotFound,
    VCInputCellMissingInMergeTx,
    FundsForVCNotLocked,
    InvalidVCMergeTx,
    FirstForceCloseFlagSet,
    FirstForceCloseFlagNotSet,
    InvalidVCLockScript,
    ParentNotFoundInOutputs,
    InvalidVersionNumberVCProgressTx,
    InvalidVCClose1Tx,
    ParentsLengthMismatch,
    ParentsMismatch,
    ParentNotInForceClose,
    VCInputCellMissingInClose1Tx,
    VCParticipantIdxNotFound,
    InvalidVCParentData,
    SUDTAllocationLengthMismatch,
    VCOutputCellMissingIngStartTx,
    VCDisputeWithoutChannelOutput,
    VCStatusNotEqual,
    NoVCRentPayoutCell,
    InvalidVCRentPayoutCell,
    LedgerChannelHasLockedFunds,
    InvalidDummyEntry,
    PoolLSNoArgs = -1,
    PoolTypescriptNotFound = -2,
    PoolInvalidCellMagic = -3,
    PoolStateTooShort = -4,
    LPPositionTooShort = -5,
    PoolStateInputMissing = -6,
    PoolStateOutputMissing = -7,
    PoolIdMismatch = -8,
    PoolReserveMismatch = -9,
    LPArithmetic = -10,
    SlippageExceeded = -11,
    OperatorNotSigning = -12,
    LPPositionInputMissing = -13,
    LPPositionPoolIdMismatch = -14,
    LPAmountZero = -15,
    LPSupplyZero = -16,
    PoolWitnessMissing = -17,
    PoolWitnessInvalid = -18,
    MultiplePoolStateCells = -19,
    PoolCKBReserveInconsistent = -20,
    PoolCKBAmountZero = -21,
    PoolAlreadyInitialised = -22,
    PoolIdInitMismatch = -23,
    ChannelAlreadyReserved = -24,
    ChannelNotReserved = -25,
    ReservationExpired = -26,
    InsufficientCKBLiquidity = -27,
    InsufficientETHLiquidity = -28,
    InvalidReservationState = -29,
    InvalidSettlement = -30,
    InvalidSwapOutput = -31,
    InvalidFeeAccounting = -32,
    NoActivePosition = -33,
    NoFeesToClaim = -34,
    InsufficientLiquidityForSwap = -35,
}
impl From<Error> for i8 {
    #[inline]
    fn from(e: Error) -> i8 {
        e as i8
    }
}

impl From<SysError> for Error {
    fn from(err: SysError) -> Self {
        use SysError::*;
        match err {
            MaxFdsCreated => Self::MaxFdsCreated,
            MaxVmsSpawned => Self::MaxVmsSpawned,
            OtherEndClosed => Self::OtherEndClosed,
            InvalidFd => Self::InvalidFd,
            WaitFailure => Self::WaitFailure,
            IndexOutOfBound => Self::IndexOutOfBound,
            ItemMissing => Self::ItemMissing,
            LengthNotEnough(_) => Self::LengthNotEnough,
            Encoding => Self::Encoding,
            Unknown(err_code) => panic!("unexpected sys error {}", err_code),
            _TypeIDError => Self::TypeIDError,
        }
    }
}

impl From<VerificationError> for Error {
    fn from(err: VerificationError) -> Self {
        use VerificationError::*;
        match err {
            TotalSizeNotMatch(_, _, _) => Self::TotalSizeNotMatch,
            HeaderIsBroken(_, _, _) => Self::HeaderIsBroken,
            UnknownItem(_, _, _) => Self::UnknownItem,
            OffsetsNotMatch(_) => Self::OffsetsNotMatch,
            FieldCountNotMatch(_, _, _) => Self::FieldCountNotMatch,
        }
    }
}

impl From<SigError> for Error {
    fn from(_: SigError) -> Self {
        return Self::SignatureVerificationError;
    }
}
