name: Rust

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
          tests/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Capsule
      run: cargo install --version 0.9.2 ckb-capsule
    - name: Build perun-common
      run: cargo build
      working-directory: contracts/perun-common
    - name: Test perun-common
      run: cargo test
      working-directory: contracts/perun-common
    - name: Build contracts
      run: capsule build
    - name: Test contracts
      run: capsule test
